# KITE NAME
kite_name: !!str "V9_60C"
# CONDITIONS
vel_wind: !!seq [0,0,6]
vel_kite: !!seq [-22, 0, 0]
acc_kite: !!seq [0, 0, 0]

## V3_25
# for testing straight-symmetric: vel_wind [20,0,2.6], stiffness = 5e5
# for testing crosswind vel_wind [0,0,4], vel_kite [-20,0,0], k=6e5

## V9_60C
# straight-symmetric v_wind[10,0,1]

# ACTUATION
##TODO: remove these old ones (first 3)
# Check first why you are using u_p here: File ~/surfdrive/phd/code/kitesim/src/initialisation/yaml_loader.py:485
# depower
u_p: !!float 1.0
depower_tape_extension_percentage: !!float 8.0
# steering
delta_ls_ini: !!float 0.01
## NEW - in meters
depower_tape_extension_step: !!float 0.01
depower_tape_final_extension: !!float 0.01
steering_tape_extension_step: !!float 0.05 #0.01
steering_tape_final_extension: !!float -0.2 #0.03

# OUTPUT SETTINGS
is_print_mid_results: !!bool true
is_with_initial_plot: !!bool false
is_with_initial_point_velocity: !!bool false
is_with_plotly_plot: !!bool false
is_with_aero_geometry: !!bool true

# SIMULATION SETTINGS
## initialisation
is_from_filename: !!bool false
bridle_initial_compression_factor:
  !!float 1.0
  # multiplication with initial length
# divides initial geometry by this factor  
geometric_scaling_factor: !!float 1
n_vel_intialisation_steps: !!int 10

## physics
is_billowing_on: !!bool true
is_with_gravity: !!bool false
is_with_aero_bridle: !!bool true
is_with_aero_tether: !!bool true
# choose either: 'NN', 'MSc_Oriol'
coupling_method: !!str 'NN'

# CASES
## reel-in symmetric straight
n_vel_initialisation_steps: !!int 10
vel_app_initial: !!seq [10, 0, 0] #initialize as array

## crosswind flight settings
tol_fx_ratio_to_fz: !!float 0.005
tol_vk_optimization: !!float 0.1
vk_x_initial_guess_factor_of_vw: !!float -3.0

## circular flight settings
is_with_varying_va: !!bool true
r_0_initial: !!float 200.0

# PHYSICAL CONSTANTS:
grav_constant: !!seq [0, 0, -9.81]
rho: !!float 1.225
mu: !!float 1.789e-5


# Aerodynamic -ChildClass: aero
AeroConfig:
  ring_geometry: !!str "5fil"
  model: !!str "VSM"
  n_iter: !!int 1500
  #error_limit used to be: 1e-5
  error_limit: !!float 1.0e-5 
  relax_factor: !!float 3.0e-2
  n_splits: !!int 2
  # With too little chordwise panels, the solver will not converge
  n_chordwise_aero_nodes: !!int 10 
  
  ## drag-coefficients
  cd_cylinder: !!float 1.1
  cd_shear_cylinder: !!float 0.02
  cd_multiplier: !!float 1.0

# Solve -  ChildClass: solver
SolverConfig:
  # method: either 'root' or 'newton'
  method: !!str "root"
  # tolerance in N, tol < calculated_total_force
  tol: !!float 20.0
  # 'root' settings (128s), use to be 500
  max_fev: !!int 2000
  integration_method: !!str "df-sane"

  # 'newton' settings (178s)
  newton_rtol: !!float 10.0
  newton_max_iter: !!int 2000
  newton_disp: !!bool false

  # alex psm settings (fed in through params-dict)
  # damping_constant --> self.__c and is a ratio --> dv = self.__c * dv
  damping_constant: !!float .9
  is_with_visc_damping: !!bool true
  dt: !!float 0.01
  n_time_steps: !!int 10000
  abs_tol: !!float 1.E-50
  rel_tol: !!float 1.E-5
  max_iter: !!int 50000
  
#  ChildClass: aerostructural
AeroStructuralConfig:
  max_iter: !!int 2500
  it_check: !!int 5
  tol: !!float 10
  # 1e-3 this is <5mm, later change to 1e-4/e-5
  crosswind_max_iter: !!int 50
  crosswind_tol: !!float 1.0e-2
  crosswind_relax_factor: !!float 0.5

TetherConfig: # set to zero, if you don't want tether force
  diameter: !!float 0.04
  length: !!float 100.0
  density: !!float 1.0


